perl -MCPAN -e "CPAN::Shell->force(qw(install PAR));"
perl -MCPAN -e "CPAN::Shell->force(qw(install Tk));"
perl -MCPAN -e "CPAN::Shell->force(qw(install Tk:DynaTabFrame));"
perl -MCPAN -e "CPAN::Shell->force(qw(install Tk:JComboBox));"
perl -MCPAN -e "CPAN::Shell->force(qw(install PAR:Packer));"
perl -MCPAN -e "CPAN::Shell->force(qw(install MP3:Tag));"